name: CI
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Prepare
        run: |
          make prepare
          go install github.com/jstemmer/go-junit-report@latest
      - name: Test
        run: |
          go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml
      - uses: test-summary/action@v2
        if: always()
        with:
          paths: report.xml
