name: Publish OCI image
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build from'
        required: false
        type: string
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PACK_VERSION: 0.28.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Install pack CLI
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v$PACK_VERSION/pack-v$PACK_VERSION-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x
      - uses: gittools/actions/gitversion/execute@v0.9.15
        id: calculate-semver
      - name: Store reckoned version into env
        run: |
          echo VERSION=${{ steps.calculate-semver.outputs.fullSemVer }}.${{ steps.calculate-semver.outputs.shortSha }} | sed 's/+/-/g' | tee -a $GITHUB_ENV
      - name: Generate go code
        run: make prepare
      - name: Build the image
        run: |
          pack build ghcr.io/${{ github.repository }} \
            --buildpack paketo-buildpacks/go \
            --builder paketobuildpacks/builder:base \
            --env BP_GO_TARGETS="./bot-discord" \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:$VERSION
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the image
        run: docker push ghcr.io/${{ github.repository }} --all-tags
      - name: Publish summary
        run: |
          echo Published image $VERSION >> $GITHUB_STEP_SUMMARY
