name: Publish OCI image
on:
  workflow_dispatch:
  # TODO: remove after testing
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PACK_VERSION: 0.28.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pack CLI
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v$PACK_VERSION/pack-v$PACK_VERSION-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - name: Generate go code
        run: make prepare
      - name: Build the image
        run: |
          pack build ghcr.io/${{ github.repository }} \
            --buildpack paketo-buildpacks/go --builder paketobuildpacks/builder:base \
            --tag ghcr.io/${{ github.repository }}:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the image
        run: docker push ghcr.io/${{ github.repository }}:latest
